name: CD
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.19.2
        id: go

      - uses: actions/checkout@v1

      - name: Build
        run: |
          go mod tidy -v
          go build cmd/scanner-trampoline/main.go -o scanner-trampoline
          
